### ISSUE TITLE
请问能提供下exp10it这个模块吗?

### ISSUE THREAD

**Issue by sherppard** [3xp10it/xenc#1]
![image](https://user-images.githubusercontent.com/7233075/43707398-9198206a-999a-11e8-9cb0-4b1050711268.png)

**Comment by 3xp10it** [comment]
[这里有][1]

[1]: https://github.com/3xp10it/exp10it

**Comment by sherppard** [comment]
谢谢！

**Comment by sherppard** [comment]
谢谢！原来你已经放出来。

**Comment by 3xp10it** [comment]
是的
